baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "Nikolai Shchelkov"
theme = "anatole"

[params]
title = "Nikolai Shchelkov"
author = "Nikolai Shchelkov"
description = """
Data Analytics, Business Intelligence, Machine Learning
Privacy-first demos only
"""
profilePicture = "images/profile.jpg"
displayMode = "auto"
favicon = "favicons/"
contactFormAction = "https://formspree.io/f/mbddorql"
customCss = ["css/custom.css"]
customJs = ["js/panynj-carousel.js", "js/about-gallery.js"]
mainSections = []

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "LinkedIn"
url = "https://www.linkedin.com/in/nikolai-s-41084119b/"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"
url = "https://instagram.com/nik91sh"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:nik91sh@gmail.com"

[menu]
  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 200
  url = "/"

  [[menu.main]]
  name = "Resume"
  identifier = "resume"
  weight = 300
  url = "/resume/"

  [[menu.main]]
  name = "Certificates"
  identifier = "certificates"
  weight = 450
  url = "/certificates/"

  [[menu.main]]
  name = "Portfolio"
  identifier = "portfolio"
  weight = 400
  url = "/portfolio/"

  [[menu.main]]
  name = "Contact"
  identifier = "contact"
  weight = 500
  url = "/contact/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ":cacheDir/images"